import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

const isPublicRoute = createRouteMatcher([
  "/",
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/terms",
  "/privacy",
  "/api/health",
  "/api/stripe/webhook",
  "/api/webhooks/clerk",
  // SEO file convention routes — generated by Next.js from sitemap.ts,
  // robots.ts, opengraph-image.tsx, twitter-image.tsx, icon.tsx,
  // apple-icon.tsx, manifest.ts. Crawlers and social media scrapers
  // must be able to fetch these without authentication.
  "/sitemap.xml",
  "/robots.txt",
  "/opengraph-image",
  "/opengraph-image(.*)",
  "/twitter-image",
  "/twitter-image(.*)",
  "/icon",
  "/icon(.*)",
  "/apple-icon",
  "/apple-icon(.*)",
  "/manifest.webmanifest",
]);

export default clerkMiddleware(async (auth, request) => {
  const { pathname } = request.nextUrl;
  if (pathname.match(/\/org\/(null|undefined)(\/|$)/)) {
    return NextResponse.redirect(new URL("/", request.url));
  }
  if (!isPublicRoute(request)) {
    await auth.protect();
  }
});

export const config = {
  matcher: [
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    "/(api|trpc)(.*)",
  ],
};
