import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

const isPublicRoute = createRouteMatcher([
  "/",
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/terms",
  "/privacy",
  "/api/health",
  "/api/stripe/webhook",
  "/api/webhooks/clerk",
  "/join(.*)",
  // Public viewer routes (Phase 2 / WSM-000061). Per-league opt-in via
  // `leagues.isPublic`; the route handlers enforce visibility through
  // publicLeagueGuard. Middleware just doesn't gate them on Clerk auth.
  "/leagues/(.*)",
  // SEO file convention routes — generated by Next.js from sitemap.ts,
  // robots.ts, opengraph-image.tsx, twitter-image.tsx, icon.tsx,
  // apple-icon.tsx, manifest.ts. Crawlers and social media scrapers
  // must be able to fetch these without authentication.
  "/sitemap.xml",
  "/robots.txt",
  "/opengraph-image",
  "/opengraph-image(.*)",
  "/twitter-image",
  "/twitter-image(.*)",
  "/icon",
  "/icon(.*)",
  "/apple-icon",
  "/apple-icon(.*)",
  "/manifest.webmanifest",
]);

// CLI BFF routes accept BOTH interactive session cookies and Clerk API keys.
// This lets the same endpoints serve in-page fetches (e.g. from a debug
// button) and out-of-band CLI calls from the sprtsmng TUI.
const isCliRoute = createRouteMatcher(["/api/cli/(.*)"]);

export default clerkMiddleware(async (auth, request) => {
  const { pathname } = request.nextUrl;
  if (pathname.match(/\/org\/(null|undefined)(\/|$)/)) {
    return NextResponse.redirect(new URL("/", request.url));
  }
  if (isCliRoute(request)) {
    await auth.protect({ token: ["session_token", "api_key"] });
    return;
  }
  if (!isPublicRoute(request)) {
    await auth.protect();
  }
});

export const config = {
  matcher: [
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    "/(api|trpc)(.*)",
  ],
};
