import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

const isPublicRoute = createRouteMatcher([
  "/",
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/terms",
  "/privacy",
  "/api/health",
  "/api/stripe/webhook",
  "/api/webhooks/clerk",
  // Vercel Cron routes carry no Clerk session — they authenticate via a
  // CRON_SECRET bearer check inside each handler. Without this, Clerk's
  // auth.protect() blocks the invocation before that check runs.
  "/api/cron/(.*)",
  "/join(.*)",
  // Visual-regression harnesses (WSM-000082) render pure presentational
  // components with fixed data and no session. They 404 in production via the
  // route handler; here they just bypass Clerk so Playwright can screenshot.
  "/dev/visual/(.*)",
  // Design-system kitchen sink (WSM-000136) — presentational only, no session.
  "/dev/ui",
  // Public viewer routes (Phase 2 / WSM-000061). Per-league opt-in via
  // `leagues.isPublic`; the route handlers enforce visibility through
  // publicLeagueGuard. Middleware just doesn't gate them on Clerk auth.
  "/leagues/(.*)",
  // Free no-login local-only tier (WSM-000137). Entirely client-rendered against
  // browser IndexedDB — no Clerk session, no Convex. Bypasses auth so a coach can
  // use it with zero friction.
  "/local",
  "/local/(.*)",
  // SEO file convention routes — generated by Next.js from sitemap.ts,
  // robots.ts, opengraph-image.tsx, twitter-image.tsx, icon.tsx,
  // apple-icon.tsx, manifest.ts. Crawlers and social media scrapers
  // must be able to fetch these without authentication.
  "/sitemap.xml",
  "/robots.txt",
  "/opengraph-image",
  "/opengraph-image(.*)",
  "/twitter-image",
  "/twitter-image(.*)",
  "/icon",
  "/icon(.*)",
  "/apple-icon",
  "/apple-icon(.*)",
  "/manifest.webmanifest",
]);

// CLI BFF routes accept BOTH interactive session cookies and Clerk API keys.
// This lets the same endpoints serve in-page fetches (e.g. from a debug
// button) and out-of-band CLI calls from the sprtsmng TUI.
const isCliRoute = createRouteMatcher(["/api/cli/(.*)"]);

export default clerkMiddleware(async (auth, request) => {
  const { pathname } = request.nextUrl;
  const requestHeaders = new Headers(request.headers);
  if (pathname === "/dashboard" || pathname.startsWith("/dashboard/")) {
    requestHeaders.set(
      "x-dashboard-path",
      `${request.nextUrl.pathname}${request.nextUrl.search}`,
    );
  }

  if (pathname.match(/\/org\/(null|undefined)(\/|$)/)) {
    return NextResponse.redirect(new URL("/", request.url));
  }
  if (isCliRoute(request)) {
    await auth.protect({ token: ["session_token", "api_key"] });
    return NextResponse.next({ request: { headers: requestHeaders } });
  }
  if (!isPublicRoute(request)) {
    // BFF API routes must answer an unauthenticated caller with a 401 JSON body
    // (every handler already implements `{ error: "Unauthorized" }`), NOT a 307
    // redirect to /sign-in — a redirect hands an API client an HTML page it
    // can't consume. `auth.protect()` redirects by default, so branch on /api
    // here and let page routes keep the sign-in redirect (WSM-000172).
    if (pathname.startsWith("/api/")) {
      const { userId } = await auth();
      if (!userId) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      }
      return NextResponse.next({ request: { headers: requestHeaders } });
    }
    await auth.protect();
  }
  return NextResponse.next({ request: { headers: requestHeaders } });
});

export const config = {
  matcher: [
    "/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
    "/(api|trpc)(.*)",
  ],
};
